version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-academic
    environment:
      POSTGRES_DB: academic_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - springnet

  academic_service:
    build: .
    container_name: academic-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/academic_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - springnet

networks:
  springnet:
    driver: bridge
